name: Notify Discord on GitHub Events

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]
  pull_request:
    types: [opened, closed, reopened, merged]
  push:
    branches: [main]  # or whatever your main branch is
  # You can add more events here like stars, forks, etc.

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          EVENT_NAME: ${{ github.event_name }}
          ACTION: ${{ github.event.action }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PUSH_REF: ${{ github.ref }}
          PUSH_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          ACTOR: ${{ github.actor }}
        run: |
          MESSAGE="Something happened on GitHub"

          if [ "$EVENT_NAME" == "issues" ]; then
            MESSAGE="📝 Issue **$ACTION**: [${ISSUE_TITLE}](${ISSUE_URL}) by $ACTOR"
          elif [ "$EVENT_NAME" == "issue_comment" ]; then
            MESSAGE="💬 Comment **$ACTION** on an issue by $ACTOR"
          elif [ "$EVENT_NAME" == "pull_request" ]; then
            MESSAGE="🔀 Pull Request **$ACTION**: [${PR_TITLE}](${PR_URL}) by $ACTOR"
          elif [ "$EVENT_NAME" == "push" ]; then
            MESSAGE="📦 Code pushed to [$PUSH_REF]($PUSH_URL) by $ACTOR"
          fi

          curl -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"$MESSAGE\"}"